# The Numpy Risk Engine 

In [3]:
import numpy as np
import pandas as pd

Exercise 1 - Create a Matrix: Generate a 10 \times 3 NumPy array of random floats representing price changes for 3 different assets over 10 days.

In [4]:
# 3 assets over 10 days - 3 columns, 2 rows

price = np.round(np.random.rand(10,3),4)
price

array([[0.9855, 0.0199, 0.9152],
       [0.7437, 0.0534, 0.9845],
       [0.9949, 0.4107, 0.2963],
       [0.6084, 0.1299, 0.5132],
       [0.9698, 0.5625, 0.9157],
       [0.9197, 0.8723, 0.1492],
       [0.2419, 0.5231, 0.1395],
       [0.6955, 0.619 , 0.0529],
       [0.3652, 0.9979, 0.3027],
       [0.6444, 0.2247, 0.1491]])

Exercise 2 - Normalization: Subtract the mean of each column from itself (centering the data).

In [57]:
mean_column1 = np.mean(price[:,0])
mean_column2 = np.mean(price[:,1])
mean_column3 = np.mean(price[:,2])


new_price = price - [mean_column1, mean_column2, mean_column3]
np.round(new_price,4)

array([[ 0.2686, -0.4214,  0.4734],
       [ 0.0268, -0.3879,  0.5427],
       [ 0.278 , -0.0306, -0.1455],
       [-0.1085, -0.3114,  0.0714],
       [ 0.2529,  0.1212,  0.4739],
       [ 0.2028,  0.431 , -0.2926],
       [-0.475 ,  0.0818, -0.3023],
       [-0.0214,  0.1777, -0.3889],
       [-0.3517,  0.5566, -0.1391],
       [-0.0725, -0.2166, -0.2927]])

Exercise 3 - Risk Calc: Calculate the Standard Deviation for each asset (column) to see which is the most volatile.

In [67]:
std_column1 = np.round(np.std(price[:,0]),4)
std_column2 = np.round(np.std(price[:,1]),4)
std_column3 = np.round(np.std(price[:,1]),4)

max_std = np.max([std_column1,std_column2,std_column3])

# this isn't necessry suggest a shorter means
if max_std == std_column1:
    print(f'the most volatile column is column1, at {max_std}')
elif max_std == std_column2:
    print(f'the most volatile column is column2, at {max_std}')
elif max_std == std_column3:
    print(f'the most volatile column is column3, at {max_std}')

the most volatile column is column2, at 0.3196


Exercise 4 - The "Crash" Scenario: Use a Boolean mask to find any days where price changes were more than 2 standard deviations from the mean

In [85]:
# Attempted copied - not mine, so i failed it

mean = new_price.mean(axis=0)
std = new_price.std(axis=0)

upper = mean + 2 * std
lower = mean - 2 * std

mask = (price > upper) | (price < lower)
mask

array([[ True, False,  True],
       [ True, False,  True],
       [ True, False, False],
       [ True, False, False],
       [ True, False,  True],
       [ True,  True, False],
       [False, False, False],
       [ True, False, False],
       [False,  True, False],
       [ True, False, False]])

# CORRECTION

Exercise 2 

In [86]:
# shorter means

new_price = price - price.mean(axis=0)
new_price

array([[ 0.2686 , -0.42144,  0.47337],
       [ 0.0268 , -0.38794,  0.54267],
       [ 0.278  , -0.03064, -0.14553],
       [-0.1085 , -0.31144,  0.07137],
       [ 0.2529 ,  0.12116,  0.47387],
       [ 0.2028 ,  0.43096, -0.29263],
       [-0.475  ,  0.08176, -0.30233],
       [-0.0214 ,  0.17766, -0.38893],
       [-0.3517 ,  0.55656, -0.13913],
       [-0.0725 , -0.21664, -0.29273]])

Exercise 3

In [87]:
# shorter means

stds = price.std(axis=0) # Gets all 3 standard deviations at once
max_idx = np.argmax(stds) # Finds the INDEX of the highest value (0, 1, or 2)

print(f"The most volatile is Column {max_idx} at {stds[max_idx]:.4f}")


The most volatile is Column 2 at 0.3468


Exercise 4

In [93]:
#shorter means

mean = new_price.mean(axis=0)
std = new_price.std(axis=0)

upper = mean + 2 * std
lower = mean - 2 * std

# Centered data (new_price) already has a mean of 0. 
# So we just check if the absolute value is > 2 standard deviations.

mask = np.abs(new_price) > (2 * price.std(axis=0))
mask

array([[False, False, False],
       [False, False, False],
       [False, False, False],
       [False, False, False],
       [False, False, False],
       [False, False, False],
       [False, False, False],
       [False, False, False],
       [False, False, False],
       [False, False, False]])